### PR TITLE
Avoiding exception for suppressed records

### LINKED ISSUE #37: The new site is mapping us to some place different
The new locator is not finding a location.  The old locator did find a location.
https://locator-prod.princeton.edu/index.php?loc=f&id=121362&embed=true
http://libwebprod.princeton.edu/locator/index.php?loc=f&id=121362&embed=true

This is because the bibdata information is suppressed for this item: https://bibdata.princeton.edu/bibliographic/121362/items

https://github.com/pulibrary/marc_liberation/issues/559

### PR DESCRIPTION
**Pull request by carolyncole**
Adds a small normalization routine since bibdata will not give us anything back for certain records

I deployed this to staging so you can see it working:
https://locator-staging.princeton.edu/index.php?loc=f&id=121362&embed=true
VS
https://locator-prod.princeton.edu/index.php?loc=f&id=121362&embed=true

fixes #37

### CODE REVIEW

File: includes/item_proc.php [hunk 1]
```diff
@@ -496,7 +496,7 @@ function loadError($item, $msg=""){
 
 			?> <a href=mailto:fstcirc@princeton.edu>fstcirc@princeton.edu</a> <?php
 
-			echo " .</p><p> Please use the <a href=\"http://libserv5.princeton.edu/requests/index.php?bib=".$_GET["id"]."\" target=\"_blank\">In Process Request</a> service if the item has no call number, is \"on order\", or is \"in the pre-order process\". </p>" . '<p>' . "$msg<br>";
+			echo " .</p><p> Please use the <a href=\"http://libserv5.princeton.edu/requests/index.php?bib=".$item->id."\" target=\"_blank\">In Process Request</a> service if the item has no call number, is \"on order\", or is \"in the pre-order process\". </p>" . '<p>' . "$msg<br>";
```
Comment (kevinreiss) [inline includes/item_proc.php]: Just use the URL pattern in https://github.com/pulibrary/firestone_locator/issues/33 instead of the old libserv5 one.
